name: question-master

services:
  client:
    image: question-master
    build:
      context: ./src/client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"
  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - question-master-data:/data/db

volumes:
  question-master-data:
